---
abstract: 'Pragmas to implement constructors and accessors'
author:
  - 'Domizio Demichelis - perl.4pro.net'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OOTools
provides:
  Class::Error:
    file: lib/Class/Error.pm
    version: 2.3
  Class::Util:
    file: lib/Class/Util.pm
    version: 2.3
  Class::constr:
    file: lib/Class/constr.pm
    version: 2.3
  Class::groups:
    file: lib/Class/groups.pm
    version: 2.3
  Class::props:
    file: lib/Class/props.pm
    version: 2.3
  Object::groups:
    file: lib/Object/groups.pm
    version: 2.3
  Object::props:
    file: lib/Object/props.pm
    version: 2.3
  Package::groups:
    file: lib/Package/groups.pm
    version: 2.3
  Package::props:
    file: lib/Package/props.pm
    version: 2.3
requires:
  perl: 5.006_001
resources:
  license: http://dev.perl.org/licenses/
version: 2.3
