# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder
version:      1.23
version_from: 
installdirs:  site
requires:
    Class::constr:                 1.62
    Class::groups:                 1.62
    Class::props:                  1.62
    IO::Util:                      1.21
    Object::groups:                1.62
    Object::props:                 1.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
