# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder
version:      1.35
version_from: lib/CGI/Builder.pm
installdirs:  site
requires:
    Class::constr:                 2.1
    Class::groups:                 2.1
    Class::props:                  2.1
    Class::Util:                   2.1
    IO::Util:                      1.46
    Object::groups:                2.1
    Object::props:                 2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
