# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder
version:      0.02
version_from: 
installdirs:  site
requires:
    Class::constr:                 1.6
    Class::props:                  1.6
    IO::Util:                      1.0
    Object::props:                 1.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
