# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder
version:      1.3
version_from: lib/CGI/Builder.pm
installdirs:  site
requires:
    Class::constr:                 2
    Class::groups:                 2
    Class::props:                  2
    Class::Util:                   2
    IO::Util:                      1.45
    Object::groups:                2
    Object::props:                 2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
