# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Magic
version:      1.22
version_from: 
installdirs:  site
requires:
    Class::constr:                 1.52
    Class::props:                  1.52
    File::Spec:                    0
    IO::Util:                      1.21
    Object::props:                 1.52

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
